### ISSUE TITLE
Figure out animations/transitions for the StartEdit related views

### ISSUE THREAD

**Issue by daividssilverio** [toggl/android#163]
## Description
This issue is here to make sure we consider animations/transitions for the StartEdit related views.
At a minimum, we consider the guidelines at https://material.io/design/motion/#principles.
Ideally, we discuss this together with our designers and figure out delightful interactions.

## Definition of done
- [x] We have a list of animations we are gonna implement or simply spec; or decide that we don't need anything special
- [x] We have a list of transitions we are gonna implement or simply spec; or decide that we don't need anything special
- [ ] The documentation is updated to reflect the changes done in this PR (Gotta document whatever we decide here, possibly sharing ideas with the iOS version)

**Comment by daividssilverio** [comment]
➿ @pdrj feature champion for the `StartEdit` views o/

**Comment by daividssilverio** [comment]
Pinging @AlicjaSuska @JanikaMandel for input.

**Comment by AlicjaSuska** [comment]
@daividssilverio when it comes to animations for start/edit views, here are some places I would pay attention to in particular:
- opening and expanding the view is prototyped here:
https://toggl.invisionapp.com/prototype/Add-Edit-Animation-ck8d0meld0065p101hflrdkjj
- dropdowns should slide up / down smoothly (like in Todoist app for ex.)
- color picker for the new project in small view - it should slide up from below the first row
(screen: https://toggl.invisionapp.com/d/main#/console/19556473/410585734/preview)
- time (duration wheel) in the small view - keyboard should be hidden (slide down) and wheel should slide up from behind the accessory (icons) view. Also, when user starts editing the duration manually, we should slide up the keyboard
(screen for reference: https://toggl.invisionapp.com/d/main#/console/19556473/409558592/preview)

**Comment by daividssilverio** [comment]
Thanks @AlicjaSuska , your comments are very helpful o/

By the way, when you say:
> dropdowns should slide up / down smoothly (like in Todoist app for ex.)

Do you mean the suggestions that appear when selecting projects/tags?

We have some basics stuff to start off. I will create issues for your points tomorrow o/

**Comment by daividssilverio** [comment]
Hey @AlicjaSuska , from your previous comment, when you said dropdowns, do you mean projects/tags like this screen? https://toggl.invisionapp.com/d/main#/console/19353169/404203826/preview#project_console

**Comment by daividssilverio** [comment]
So, for the list of specs for the for the StartEdit view:
- [ ] [We need to ensure that the StartEdit view's expanding animation/transition is smooth.](https://github.com/toggl/android/issues/248)
- [ ] [The dropdowns* (probably the auto complete suggestions) also animate smoothly.](https://github.com/toggl/android/issues/249)
- [ ] [In the Add Project view, the color picker should appear from the bottom of the screen, transitioning smoothly as well.](https://github.com/toggl/android/issues/250)

**Comment by daividssilverio** [comment]
@AlicjaSuska about the color picker view in the "Expanded Add project" view, how are the animations/transitions supposed to work there?

Should we just slide down the color picker view into the layout? Or simply fade in/out?

**Comment by AlicjaSuska** [comment]
@daividssilverio by dropdowns I mean both - suggestions and those from project/tag pills

about the wheel - we should fad it in and slide the view a little so that the whole wheel is visible :)

**Comment by daividssilverio** [comment]
Alright about the dropdowns. @AlicjaSuska . 
For the fade in & slide, you're talking about the color picker, right? The wheel doesn't appear in the "expanded add project" view. I'll assume that and create the issue.

**Comment by daividssilverio** [comment]
Completing the list considering the last comments from @AlicjaSuska 

So, for the list of specs for the for the StartEdit view:
- [ ] [We need to ensure that the StartEdit view's expanding animation/transition is smooth.](https://github.com/toggl/android/issues/248)
- [ ] [The dropdowns (auto complete suggestions, tags, projects) animate smoothly.](https://github.com/toggl/android/issues/249)
- [ ] [In the Small Add Project view, the color picker should appear from the bottom of the screen, transitioning smoothly as well.](https://github.com/toggl/android/issues/250)
- [ ] [In the Expanded Add Project view, the color picker should slide in to appear on screen](https://github.com/toggl/android/issues/286)

**Comment by daividssilverio** [comment]
I think we can consider this issue closed unless @AlicjaSuska has something else to add.
➿ @heytherewill

**Comment by daividssilverio** [comment]
Ping @sofokli1 about the ideas here that might apply to the iOS version as well.

**Comment by heytherewill** [comment]
Since no other activity was added in 4 days, I'm closing this issue :)
